DEFAULT_MCP_READ_TIMEOUT_SECONDS = 5 # SECONDS
DEFAULT_CONNECTION_TIMEOUT_SECONDS = 5 # SECONDS
MIN_CONNECTION_TIMEOUT_SECONDS = 1 # second
MAX_CHARACTERS_TO_RETURN = 10000
MAX_ALLOWED_TOOLS = 200
DEFAULT_AUTO_APPROVE = False
